### ISSUE TITLE
Not working on 1.16.5

### ISSUE THREAD

**Issue by Bloodlex** [Falyrion/AdvancedArmorStands#1]
Hello,

I can't run this plugin on 1.16.5.

`[17:36:55] [Server thread/ERROR]: Could not load 'plugins/AdvancedArmorStands.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.17
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:361) ~[patched_1.16.5.jar:git-Purpur-1169]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.16.5.jar:git-Purpur-1169]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Purpur-1169]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Purpur-1169]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Purpur-1169]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:279) ~[patched_1.16.5.jar:git-Purpur-1169]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1169]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1169]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

Could you please help? Thanks!

**Comment by Falyrion** [comment]
Hey,

This plugin was made for spigot 1.17+ and will not work with older versions.
I recompiled a version that should work with spigot 1.16+ for you. Just download the .jar file from the [1.16 release page](https://github.com/Falyrion/AdvancedArmorStands/releases/tag/v1.16.1.0).

I will not continue support for older spigot versions in the future.
